---
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: selora/ocode-ex
    command: sleep infinity
    volumes:
      - ..:/workspaces/ocode-ex
    tty: true
    stdin_open: true
    # force a login shell so /etc/profile.d/nix.sh runs if present
